In [3]:
import numpy as np

In [ ]:
# Content
1. Create
2. Select
3. Matrix Computation

## 1. Create array

In [5]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [7]:
np.random.randint(0,6)

3

In [9]:
a = np.array([[2,3],[4,2]])
a

array([[2, 3],
       [4, 2]])

In [11]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 2. Select

In [31]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
a>3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [13]:
a[a>3]

array([4, 5, 6, 7, 8])

In [33]:
np.where(a>3,1,2)

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

## 3. Matrix Computation

In [15]:
a = np.random.randn(4,4)

In [16]:
a.T

array([[-0.59995695,  0.13926787, -0.88431028, -0.87503745],
       [ 0.68839198,  0.67700373,  0.30652144,  0.29610442],
       [ 0.02754208, -1.2891795 ,  0.3648755 ,  1.17367979],
       [ 1.43108755, -0.44186228, -0.96162842,  0.87727603]])

In [17]:
a.dot(a.T)

array([[ 2.88260202, -0.28536109, -0.62457003,  2.0166051 ],
       [-0.28536109,  2.33495564,  0.03887747, -1.82211992],
       [-0.62457003,  0.03887747,  1.93382341,  0.4492004 ],
       [ 2.0166051 , -1.82211992,  0.4492004 ,  3.00050585]])

In [18]:
# Get diag values
np.diag( a)

array([-0.59995695,  0.67700373,  0.3648755 ,  0.87727603])

## 4. Common Operation

In [24]:
a = np.arange(-5,4).reshape((3,3))
a

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3]])

In [23]:
np.abs(a)

array([[5, 4, 3],
       [2, 1, 0],
       [1, 2, 3]])

In [25]:
np.mean(a)

-1.0

In [26]:
np.sqrt(a)

array([[       nan,        nan,        nan],
       [       nan,        nan, 0.        ],
       [1.        , 1.41421356, 1.73205081]])

In [27]:
np.square(a)

array([[25, 16,  9],
       [ 4,  1,  0],
       [ 1,  4,  9]], dtype=int32)

In [28]:
np.exp(a)

array([[6.73794700e-03, 1.83156389e-02, 4.97870684e-02],
       [1.35335283e-01, 3.67879441e-01, 1.00000000e+00],
       [2.71828183e+00, 7.38905610e+00, 2.00855369e+01]])